# Generated by Django 3.1.6 on 2021-10-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdeuctModel',
            new_name='ProductModel',
        ),
    ]
